Controllers/alunosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Xdevs.Inscricao.Models;

namespace Xdevs.Inscricao.Controllers
{
    public class AlunosController : Controller
    {
        private Context db = new Context();

        public ActionResult Index()
        {
            return View();
        }

        // GET: alunos
        [Authorize]
        public ActionResult List()
        {
            return RedirectToAction("Index");
            //return View(db.Alunos.ToList());
        }

        // GET: alunos/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            return RedirectToAction("Index");
            //if (id == null)
            //{
            //    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            //}
            //Aluno aluno = db.Alunos.Find(id);
            //if (aluno == null)
            //{
            //    return HttpNotFound();
            //}
            //return View(aluno);
        }

        // GET: alunos/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: alunos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,NomeCompleto,CPF,Email,Celular,Whatsapp,CEP,Endereco,EndNumero,EndComplemento,Bairro,Cidade,Estado")] Aluno aluno)
        {
            if (ModelState.IsValid)
            {
                db.Alunos.Add(aluno);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(aluno);
        }

        // GET: alunos/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            return RedirectToAction("Index");
            //if (id == null)
            //{
            //    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            //}
            //Aluno aluno = db.Alunos.Find(id);
            //if (aluno == null)
            //{
            //    return HttpNotFound();
            //}
            //return View(aluno);
        }

        // POST: alunos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,NomeCompleto,CPF,Email,Celular,Whatsapp,CEP,Endereco,EndNumero,EndComplemento,Bairro,Cidade,Estado")] Aluno aluno)
        {
            if (ModelState.IsValid)
            {
                db.Entry(aluno).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(aluno);
        }

        // GET: alunos/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            return RedirectToAction("Index");
            //if (id == null)
            //{
            //    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            //}
            //Aluno aluno = db.Alunos.Find(id);
            //if (aluno == null)
            //{
            //    return HttpNotFound();
            //}
            //return View(aluno);
        }

        // POST: alunos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Aluno aluno = db.Alunos.Find(id);
            db.Alunos.Remove(aluno);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Cursos XDevs</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Cursos XDevs", "Index", "Alunos", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Início", "Index", "Alunos")</li>
                    <li>@Html.ActionLink("Inscrição", "Create", "Alunos")</li>
                    <li>@Html.ActionLink("Gerenciamento", "List", "Alunos")</li>
                    <li>@Html.ActionLink("Login", "Login", "Login")</li>
                    <li>@Html.ActionLink("Registro", "Register", "Login")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Cursos XDevs</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>